# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    id: macos
    goos:
      - darwin
    main: ./cmd/kana/main.go
    binary: kana
    ldflags:
      - -s -w -X github.com/ChrisWiegman/kana-cli/internal/cmd.Version={{.Version}} -X github.com/ChrisWiegman/kana-cli/internal/cmd.GitHash={{.Commit}} -X github.com/ChrisWiegman/kana-cli/internal/cmd.Timestamp={{.Date}}
archives:
  - replacements:
      darwin: Darwin
      386: i386
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-devel"
changelog:
  skip: false
brews:
  - tap:
      owner: ChrisWiegman
      name: homebrew-kana
      branch: main
    name: kana
    license: "GPL-3.0 license"
    test: |
      system "#{bin}/kana version"
    homepage: "https://github.com/ChrisWiegman/kana-cli"
    description: "A simple, portable CLI for efficient WordPress development."
