project_name: kana

env:
  - CGO_ENABLED=0

before:
  hooks:
    - go mod tidy

builds:
  - id: macos
    goos:
      - darwin
    main: ./cmd/kana/main.go
    binary: kana
    ldflags:
      - -s -w -X github.com/ChrisWiegman/kana-cli/internal/cmd.Version={{.Version}} -X github.com/ChrisWiegman/kana-cli/internal/cmd.GitHash={{.Commit}} -X github.com/ChrisWiegman/kana-cli/internal/cmd.Timestamp={{.Date}}

archives:
  - id: macos
    builds: [macos]
    format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      amd64: x86_64
      darwin: macos
    files:
      - LICENSE.txt
      - CHANGELOG.md

snapshot:
  name_template: "{{ incpatch .Version }}-devel"

changelog:
  skip: false

brews:
  - tap:
      owner: ChrisWiegman
      name: homebrew-kana
      branch: main
    name: kana
    license: "GPL-3.0 license"
    test: |
      system "#{bin}/kana version"
    homepage: "https://github.com/ChrisWiegman/kana-cli"
    description: "A simple, portable CLI for efficient WordPress development."
