version: 2

project_name: kana

env:
  - CGO_ENABLED=0

before:
  hooks:
    - go mod tidy

builds:
  - id: macos
    goos:
      - darwin
    main: ./cmd/kana/main.go
    binary: kana
    ldflags:
      - -s -w -X github.com/ChrisWiegman/kana-wordpress/internal/cmd.Version={{.Version}} -X github.com/ChrisWiegman/kana-wordpress/internal/cmd.Timestamp={{.Date}}
  - id: linux
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/kana/main.go
    binary: kana
    ldflags:
      - -s -w -X github.com/ChrisWiegman/kana-wordpress/internal/cmd.Version={{.Version}} -X github.com/ChrisWiegman/kana-wordpress/internal/cmd.Timestamp={{.Date}}

archives:
  - id: macos
    builds:
      - macos
      - linux
    format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- if eq .Os "darwin" }}macos
      {{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - LICENSE.txt
      - CHANGELOG.md

snapshot:
  name_template: "{{ incpatch .Version }}-devel"

changelog:
  disable: false

nfpms:
  - vendor: Chris Wiegman
    builds:
      - linux
    license: GPL-3.0 license
    homepage: https://github.com/ChrisWiegman/kana-wordpress
    maintainer: Chris Wiegman <contact@chriswiegman.com>
    description: A simple, portable CLI for efficient WordPress development.
    file_name_template: >-
      {{ .ProjectName }}_
      {{-  .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    formats:
      - apk
      - deb
      - rpm
      - archlinux

brews:
  - repository:
      owner: ChrisWiegman
      name: homebrew-kana
      branch: main
    name: kana
    license: GPL-3.0 license
    test: |
      system "#{bin}/kana version"
    homepage: https://github.com/ChrisWiegman/kana-wordpress
    description: A simple, portable CLI for efficient WordPress development.
