version: "3"

networks:
  default:
    driver: bridge

services:
  traefik:
    image: traefik:2.7
    networks:
      - default
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    restart: always
    volumes:
      - ./internal/setup/source/traefik.toml:/etc/traefik/traefik.toml
      - ./internal/setup/source/dynamic.toml:/etc/traefik/dynamic.toml
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users/chriswiegman/.kana/certs:/var/certs

  mariadb:
    depends_on:
      - watchtower
    environment:
      - MYSQL_ROOT_PASSWORD=Mi11erLite
    image: mariadb:10
    networks:
      - default
    ports:
      - 3306:3306
    restart: always

  wordpress:
    depends_on:
      - mariadb
      - traefik
    image: wordpress
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.wordpress-https.redirectscheme.scheme=https"
      - "traefik.http.routers.wordpress-http.entrypoints=web"
      - "traefik.http.routers.wordpress-http.rule=Host(`wordpress.local.dev`)"
      - "traefik.http.routers.wordpress-http.middlewares=wordpress-https@docker"
      - "traefik.http.routers.wordpress.entrypoints=web-secure"
      - "traefik.http.routers.wordpress.rule=Host(`wordpress.local.dev`)"
      - "traefik.http.routers.wordpress.tls=true"
      - "traefik.http.services.wordpress-service.loadbalancer.server.port=80"
    networks:
      - default
    restart: always
