name: Lint

on:
  push:
    branches:
      - main
      - develop
    tags-ignore:
      - "**"
  pull_request:
    types: [opened,synchronize,ready_for_review,edited]

# Cancel previous workflow run groups that have not completed.
concurrency:
  # Group workflow runs by workflow name, along with the head branch ref of the pull request
  # or otherwise the branch or tag ref.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  golangci-lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
