name: release

on:
  push:
    branches: [main]
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch all tags
        run: git fetch --force --tags

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Add env vars
        run: |
          echo RELEASE_NOTES_PATH=.changes/$(shell git describe --tags || echo "0.0.1").md >> $GITHUB_ENV

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3.1.0
        with:
          version: latest
          args: --rm-dist --release-notes=${{ env.RELEASE_NOTES_PATH }} --skip-validate --debug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
