name: release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Add env vars
        run: |
          echo RELEASE_NOTES_PATH=.changes/${{ github.ref_name }}.md >> $GITHUB_ENV

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3.2.0
        with:
          version: latest
          args: --rm-dist --release-notes=${{ env.RELEASE_NOTES_PATH }} --skip-validate --debug
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
