name: Test

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  go-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Install Latest Docker
        run: |
          sudo install -m 0755 -d /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          sudo chmod a+r /etc/apt/keyrings/docker.gpg
          echo \
            "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
            "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
            sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Setup a Browser
        uses: browser-actions/setup-chrome@v1

      - name: Test the browser
        run: |
          xdg-settings --list

      - name: Build test cli
        run: |
          go mod vendor
          go build \
            -o ./build/kana \
            -ldflags "-s -w -X github.com/ChrisWiegman/kana/internal/cmd.Version=1.0.0 -X github.com/ChrisWiegman/kana/internal/cmd.Timestamp=2024-03-16_10:50:11PM" \
            ./cmd/...
          go test ./...

      - name: Test
        uses: robherley/go-test-action@v0.2.0
